### ISSUE TITLE
Fix sticky doc header - documenter themes

### ISSUE THREAD

**Issue by icweaver** [JuliaComputing/MultiDocumenter.jl#92]
Is it possible for #46 to persist after switching to one of Documenter's new themes? It currently seems to override MultiDocumenter's css when scrolling back up on mobile. [Example site](https://juliaastro.org/):

![Image](https://github.com/user-attachments/assets/9112679d-30d8-40de-a16b-d95b30d4243d)
![Image](https://github.com/user-attachments/assets/6cd8506e-0341-4c34-ba08-d8f0abe455b6)

## Default theme
Scroll down:
```css
# multidoc.css
@media screen and (max-width: 1055px) {
    #documenter .docs-main header.docs-navbar.headroom--unpinned.headroom--not-top.headroom--not-bottom {
        top: -100vh;
    }
}
```

Scroll up:

```css
# multidoc.css
@media screen and (max-width: 1055px) {
    #documenter .docs-main header.docs-navbar {
        top: var(--navbar-height);
    }
}
```

## New theme (e.g., catppuccin-latte)
Scroll down:

```css
# catppuccin-latte.css
@media screen and (max-width: 1055px) {
    html.theme--catppuccin-latte #documenter .docs-main header.docs-navbar.headroom--unpinned.headroom--not-top.headroom--not-bottom {
        top: -4.5rem;
    }
}
```

Scroll up:
```css
# catppuccin-latte.css
@media screen and (max-width: 1055px) {
    html.theme--catppuccin-latte #documenter .docs-main header.docs-navbar {
        position: sticky;
        top: 0;
        padding: 0 1rem;
    }
}
```
